title: "LQC Studios"
description: "Low Quality Creations — high-effort games & ideas."
url: "https://lqcstudios.ca"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

nav:
  - title: Home
    url: "/"
  - title: Projects
    url: "/projects/"
  - title: About
    url: "/about/"
  - title: Contact
    url: "/contact/"

brand:
  name: "LQC"
  accent: "#ff3b3b"
